#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/ permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
#insert the text  in line befor line 46 befor represented by i  
sudo sed -i "46i error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
